[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "geoaquacrop_simulate"
version = "0.1.0"             
description = "Gridded AquaCrop-OSPy simulation runner"
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
license-files = ["LICENSE"]     
authors = [
    { name = "Josias Lang-Ritter" },
    { name = "Christopher Bowden" },
    { name = "Seyed Hossein Hosseini" },
    { name = "Henrikki Tenkanen" },
    { name = "Timothy Foster" },
    ]

maintainers = [
    { name = "Christopher Bowden", email = "christopher.bowden@manchester.ac.uk" },
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Scientific/Engineering :: Hydrology",
]

dependencies = [
    "numpy",
    "pandas",
    "xarray>=2025.1",
    "netcdf4",
    "tqdm",
    "aquacrop>=3.1.0", # guarantee CO2 scenario-specific files                  
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov"]
correction = ["geopandas", "matplotlib"]   # yield correction + comparison figures
docs = ["sphinx>=7", "furo"]


[project.urls]
Documentation = "https://geoaquacrop-simulate.readthedocs.io/en/stable/"
Homepage = "https://github.com/aquacropos/geoaquacrop_simulate"
Preprocessing = "https://github.com/aquacropos/geoaquacrop_preprocess"
Visualization = "https://github.com/aquacropos/geoaquacrop_visualize"


[project.scripts]
geoaquacrop_simulate = "geoaquacrop_simulate.run_aquacrop:main"

[tool.setuptools.packages.find]
where = ["src"]
